
services:
  # --- Base de Datos ---
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: dvaldebenito       # Coincide con tu user en .env
      POSTGRES_PASSWORD: Daniel2507!    # Coincide con tu pass en .env
      POSTGRES_DB: RavenTest            # Coincide con tu DB en .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dvaldebenito -d RavenTest"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Backend (Node.js) ---
  backend:
    build: ./backend
    container_name: node_backend
    ports:
      - "${PORT}:${PORT}" # Mapea 3001:3001
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules

  # --- Frontend (React) ---
  frontend:
    build: ./frontend # Usará tu fDockerfile (asegúrate de que EXPOSE sea 5173)
    container_name: react_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_TARGET=${VITE_API_TARGET} # Pasa la variable al contenedor para vite.config.js
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
  
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    restart: always
    # Apuntamos al nombre del servicio 'frontend' y su puerto interno
    command: tunnel --url http://frontend:5173
    depends_on:
      - frontend
volumes:
  postgres_data:
